<?php $this->extend('base'); ?>

<div class="box">
    <h2 class="title success">Welcome</h2>

    <div class="block">
        <p>Congratulations! You have successfully installed a new Quice application. You man change the content of this page by modifying the following files:</p>

        <ul>
            <li>Module file: /myproject/src/MyProject/Core/CoreModule.php</li>
            <li>Action file: /myproject/src/MyProject/Core/IndexAction.php</li>
        </ul>

        <p>For more details on how to further develop this application, please read the <a href="<?php echo $url->href('dev', 'doc'); ?>">document</a>.</p>
    </div>
</div>