<style type="text/css">
/* Html & body
 * -------------------------------------------------------------------------- */
html { height: 100%; padding-bottom: 1px; /* force scrollbars */ }
body {
    color: #333;
    padding: 0 0 40px;
    font: 13px/1.5 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif;
    background-color: #F0F7FC;
}

/* Anchors
 * -------------------------------------------------------------------------- */
a { color:#114488; text-decoration: underline; }
a:hover { color:#114488; background-color: #ddeeff; text-decoration: none; }
a:active { background-color: #FFA500; color:white; text-decoration: none; }

/* Typography
 * -------------------------------------------------------------------------- */
p { font-size: 13px;font-weight: normal;line-height: 18px;margin-bottom: 9px; }
p small { font-size: 11px;color: #bfbfbf; }

h1, h2, h3, h4, h5, h6 { font-weight: bold;color: #404040; }
h1 small, h2 small, h3 small, h4 small, h5 small, h6 small { color: #bfbfbf; }
h3, h4, h5, h6 { line-height: 30px; }
h1 { font-size: 20px; }
h1 small { font-size: 18px; }
h2 { font-size: 18px; }
h2 small { font-size: 16px; }
h3 { font-size: 16px; }
h3 small { font-size: 14px; }
h4 { font-size: 14px; }
h4 small { font-size: 12px; }
h5 { font-size: 13px; }
h6 { font-size: 12px; color: #bfbfbf; text-transform: uppercase; }

ul, ol { margin: 0 0 18px 25px; }
ul ul, ul ol, ol ol, ol ul { margin-bottom: 0; }
ul { list-style: disc; }
ol { list-style: decimal; }
li { line-height: 18px; color: #808080; }
ul.unstyled { list-style: none; margin-left: 0; }
dl { margin-bottom: 18px; }
dl dt, dl dd { line-height: 18px; }
dl dt { font-weight: bold; }
dl dd { margin-left: 9px; }
hr { margin: 20px 0 19px; border: 0; border-bottom: 1px solid #eee; }
strong { font-style: inherit; font-weight: bold; }
em { font-style: italic; font-weight: inherit; line-height: inherit;}
.muted { color: #bfbfbf; }
blockquote { margin-bottom: 18px; border-left: 5px solid #eee; padding-left: 15px; }
blockquote p { font-size: 14px; font-weight: 300; line-height: 18px; margin-bottom: 0; }
blockquote small { display: block; font-size: 12px; font-weight: 300; line-height: 18px; color: #bfbfbf; }
blockquote small:before { content: '\2014 \00A0'; }
address { display: block; line-height: 18px; margin-bottom: 18px; }
code, pre { padding: 0 3px 2px; font-family: Monaco, Andale Mono, Courier New, monospace; font-size: 12px; }
code { color: green; padding: 1px 3px; }
code span { font-weight: bolder; background-color: #ffc; }
pre {
    background-color: #fefefe; display: block; padding: 8.5px; margin: 0 0 18px; line-height: 18px;
    font-size: 12px; border: 1px solid #eee;
    white-space: pre; white-space: pre-wrap; word-wrap: break-word;
}
.highlight { background-color: #fee9cc; }
.em {color:orange;}
.container {margin:2%;}

/* Box
 * -------------------------------------------------------------------------- */
.box { background:white; margin-bottom:10px; padding:0; border:1px solid #CED5DB; }
.box .title {
    font-size:14px;
    line-height: 16px;
    font-weight:bold;
    margin:0;
    padding:8px 12px;
    background-color: #f5f5f5;
    text-shadow: #aaa 0px 2px 2px;
    border-bottom:1px solid #f2f2f2;
}
.box .title small {
    font-size:12px;
    font-weight:normal;
    color:#999;
    text-shadow: none;
}
.box .title a,
.box .title a.visible { color:#333; text-decoration:none; }
.box .title a:hover { color:#333; text-decoration:underline; }
.box .title a:active { color:#fff; text-decoration:none; }
.box .block { margin:10px; }
.box .title.error { background-color: #c43c35; color: #ffffff; }
.box .title.success { background-color: #57a957; color: #ffffff; }
.box .title.info { background-color: #5BC0DE; color: #ffffff;s }


/* Nav
 * -------------------------------------------------------------------------- */
.nav {
  margin: 0;
  padding: 7px 14px;
  background-color: #f5f5f5;
  border-bottom:#f0f0f0;
}
.nav li {
  display: inline;
  text-shadow: 0 1px 0 #ffffff;
}
.nav .divider {
  padding: 0 5px;
  color: #bfbfbf;
}
.nav .active a {
  color: #404040;
}
</style>