<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Quice</title>
<link href="<?php echo $url->href('core', 'style'); ?>"
    rel="stylesheet" type="text/css" media="screen" />
</head>
<body>

<div style="margin:5%;">
    <?php echo $this->getChild(); ?>
    <p style="color:grey;text-align:center;">Build with Quice.</p>
</div>

</body>
</html>